[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = false

[colors.primary]
background = "#0d0f1f"
foreground = "#f2f2f2"

# Normal colors
[colors.normal]
black = "#1b1d2b"
red = "#ff757f"
green = "#c3e88d"
yellow = "#ffc777"
blue = "#82aaff"
magenta = "#c099ff"
cyan = "#86e1fc"
white = "#d0d7f4"

# Bright colors
[colors.bright]
black = "#444a73"
red = "#ff757f"
green = "#c3e88d"
yellow = "#ffc777"
blue = "#82aaff"
magenta = "#c099ff"
cyan = "#86e1fc"
white = "#d8e0f8"

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = "#ff966c"

[[colors.indexed_colors]]
index = 17
color = "#c53b53"

[colors.hints.end]
background = "#1d1f21"
foreground = "#e9ff5e"

[colors.hints.start]
background = "#e9ff5e"
foreground = "#1d1f21"

[colors.search.matches]
background = "#E5C07B"
foreground = "#3E4452"

[cursor]
blink_interval = 500

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 16

[font.normal]
family = "FiraCode Nerd Font"
style = "Medium"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F12"

[[keyboard.bindings]]
chars = "\u001B[91;5u"
key = "LBracket"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000

[window]
decorations = "none"
opacity = 0.95
