[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = false

[colors.primary]
background = "#0d0f1f"
foreground = "#f2f2f2"

# Normal colors
[colors.normal]
black = "#1b1d2b"
red = "#ff757f"
green = "#c3e88d"
yellow = "#ffc777"
blue = "#82aaff"
magenta = "#c099ff"
cyan = "#86e1fc"
white = "#d0d7f4"

# Bright colors
[colors.bright]
black = "#444a73"
red = "#ff757f"
green = "#c3e88d"
yellow = "#ffc777"
blue = "#82aaff"
magenta = "#c099ff"
cyan = "#86e1fc"
white = "#d8e0f8"

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = "#ff966c"

[[colors.indexed_colors]]
index = 17
color = "#c53b53"

[colors.hints.end]
background = "#1d1f21"
foreground = "#e9ff5e"

[colors.hints.start]
background = "#e9ff5e"
foreground = "#1d1f21"

[colors.search.matches]
background = "#E5C07B"
foreground = "#3E4452"

[cursor]
blink_interval = 500

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 18

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

[mouse]
hide_when_typing = true

[scrolling]
history = 100000

[window]
decorations = "none"
opacity = 0.95

[keyboard]
bindings = [
  # toggle fullscreen
  { key = "F12", action = "ToggleFullscreen"},

  # map Command + x to Alt + c (FZF go to directory)
  { key = "X",      mods = "Command",       chars = "\u001Bc" },

  # map Command + h,j,k,l to Alt + h,j,k,l
  { key = "J",      mods = "Command",       chars = "\u001Bj" },
  { key = "H",      mods = "Command",       chars = "\u001Bh" },
  { key = "K",      mods = "Command",       chars = "\u001Bk" },
  { key = "L",      mods = "Command",       chars = "\u001Bl" },

  # map Command + H,J,K,L to Alt + H,J,K,L
  { key = "J",      mods = "Command|Shift", chars = "\u001BJ" },
  { key = "H",      mods = "Command|Shift", chars = "\u001BH" },
  { key = "K",      mods = "Command|Shift", chars = "\u001BK" },
  { key = "L",      mods = "Command|Shift", chars = "\u001BL" },
]
